package com.springmvc.dao;

import com.springmvc.pojo.SlDataBasketballWithBLOBs;

public interface SlDataBasketballMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sl_data_basketball
     *
     * @mbggenerated
     */
    int insert(SlDataBasketballWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sl_data_basketball
     *
     * @mbggenerated
     */
    int insertSelective(SlDataBasketballWithBLOBs record);
}