package com.springmvc.dao;

import com.springmvc.pojo.SlDataTradWithBLOBs;

public interface SlDataTradMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sl_data_trad
     *
     * @mbggenerated
     */
    int insert(SlDataTradWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sl_data_trad
     *
     * @mbggenerated
     */
    int insertSelective(SlDataTradWithBLOBs record);
}